Page({
  data:{
    name:'szq',
    students:[
      {id:1,name:'q',age:23},
      {id:2,name:'w',age:22},
      {id:1,name:'e',age:25},
    ],
    counter:0
  },
  subclick(){
    this.setData({
      counter:this.data.counter-1
    })
  },
  addclick(){
    this.setData({
      counter:this.data.counter+1
    })
  }
})